update

diff --git a/.github/workflows/deploy-domain.yml b/.github/workflows/deploy-domain.yml
--- a/.github/workflows/deploy-domain.yml
+++ b/.github/workflows/deploy-domain.yml
@@ -38,12 +38,7 @@ jobs:
                 if [ -f "$file" ]; then
                   echo "Applying $file..."
                   start=$(date +%s)
-                  output=$(kubectl apply --timeout=60s -f "$file" 2>&1)
-                  if echo "$output" | grep -q 'namespaces .* not found'; then
-                    echo "⚠️  Bỏ qua $file do namespace chưa tồn tại."
-                  else
-                    echo "$output"
-                  fi
+                  kubectl apply --timeout=60s -f "$file" 2>&1 || echo "❌ Error applying $file"
                   end=$(date +%s)
                   echo "Done $file in $((end-start))s"
                 fi
